# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
      exclude: "static/.*"
      exclude_types:
        - svg
    - id: end-of-file-fixer
      exclude: "static/.*"
      exclude_types:
        - svg
    - id: check-yaml
      exclude: "static/.*"
      types:
        - file
        - yaml
      exclude_types:
        - svg
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.9
      types:
        - file
        - python

- repo: https://github.com/pycqa/flake8
  rev: '21d3c70d'
  hooks:
    - id: flake8
      types:
        - file
        - python
